### PR TITLE
Fix user deletion #6

### LINKED ISSUE #6: Problem with user-deletion
Hello there

we use local_ws_enrolcohort when syncing our users to cohorts and into the courses by a python script (connecting to the REST API of Moodle).

While testing we also had to delete some users. For those users the GDPR-settings automatically created deletion entries, which we accepted.

From then on the cronjob did not finish any longer but failed after some time with an fatal php-error (it took us some time to find out). The messages was:

Declaration of local_ws_enrolcohort\privacy\provider::get_reason() must be compatible with core_privacy\local\metadata\null_provider::get_reason()

I have no idea if this is related but I know, when I remove the plugin, the cronjob works as it should.

Best regards
thoschi

### PR DESCRIPTION
**Pull request by OndroNR**
Fixes #6

### CODE REVIEW

File: classes/privacy/provider.php [hunk 1]
```diff
@@ -38,7 +38,7 @@ class provider implements null_provider {
      *
      * @return string
      */
-    public static function get_reason() {
+    public static function get_reason(): string {
```
Comment (emyb2) [inline classes/privacy/provider.php:41]: Thanks for this, can you add a space please 😅
```suggestion
    public static function get_reason() : string {
```

**Review by emyb — APPROVED** [review]

**Comment by emyb** [comment]
Thank you for your contribution @OndroNR \o/
